modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="behamotten"
version="${file.jarVersion}"
displayName="Behamotten Event Tools"
description="Provides commands to manage event participants on the server."
author="Behamotten"

[[dependencies.behamotten]]
modId="neoforge"
type="required"
versionRange="[21.1.209,)"
ordering="NONE"
side="BOTH"

[[dependencies.behamotten]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.1]"
ordering="NONE"
side="BOTH"
