name: BehamottenEventTools
main: com.behamotten.events.BehamottenEventsPlugin
version: 0.1.0
api-version: '1.20.6'
authors:
  - Behamotten
commands:
  setevents:
    description: Registriert den Spieler f체r Event-Aktionen.
    usage: /setevents
    permission: behamotten.setevents
  unsetevents:
    description: Entfernt den Spieler aus der Eventliste.
    usage: /unsetevents
    permission: behamotten.unsetevents
  getalleventuser:
    description: Listet registrierte Event-Teilnehmer auf oder w채hlt einen zuf채llig aus.
    usage: /getalleventuser [@r]
    permission: behamotten.getall
  generatequestmaster:
    description: Erstellt die FTB-Quest-Masterdatei neu.
    usage: /generatequestmaster
    permission: behamotten.progress.quest
  generateadvancementmaster:
    description: Erstellt die Advancement-Masterdatei neu.
    usage: /generateadvancementmaster
    permission: behamotten.progress.advancement
permissions:
  behamotten.setevents:
    description: Erlaubt einem Spieler, sich f체r Events zu registrieren.
    default: true
  behamotten.unsetevents:
    description: Erlaubt einem Spieler, sich von Events abzumelden.
    default: true
  behamotten.getall:
    description: Erlaubt das Anzeigen aller registrierten Event-Teilnehmer.
    default: op
  behamotten.progress.quest:
    description: Erlaubt das Erstellen der Quest-Masterdatei.
    default: op
  behamotten.progress.advancement:
    description: Erlaubt das Erstellen der Advancement-Masterdatei.
    default: op
